### ISSUE TITLE
only show leading and trailing white space

### ISSUE THREAD

**Issue by sevenfoxes** [DennisKehrig/brackets-show-whitespace#22]
Thought I'd throw my two cents in here... I don't like seeing the spaces between attributes in my html tags. I also think that the contrast is still too strong  but that's probably user preference at this point. Here's what i've adjusted on the "obsidian" theme:

.CodeMirror .cm-dk-whitespace-leading-space:before, .CodeMirror .cm-dk-whitespace-leading-tab:before{
	background: #667a82;
}
.CodeMirror .cm-dk-whitespace-space:before, .CodeMirror .cm-dk-whitespace-tab:before {
	background-color: transparent;
}

![untitled-1](https://cloud.githubusercontent.com/assets/809000/3220871/0bdbd9be-f005-11e3-8822-d5cd3cf7b487.jpg)

**Comment by DennisKehrig** [comment]
Hey @sevenfoxes, did you adjust this only locally or is it part of the theme for everyone now? The latter would be terrific!

As far as this feature request is concerned, your wish makes sense. Personally, I'd want the code to distinguish between semantic marking of whitespace (leading, trailing, other) and what colors to use, so an implementation should only change the color for "other", not remove the classification altogether.

**Comment by le717** [comment]
@DennisKehrig Setting `.CodeMirror .cm-dk-whitespace-space:before, .CodeMirror .cm-dk-whitespace-tab:before` to use a different color can be easily done with a minor expansion to #30. I just have to add a new item in the arrays and use it, if that is what you meant.

**Comment by sevenfoxes** [comment]
@DennisKehrig I did not push this change. Actually no longer have that computer either ha!

**Comment by le717** [comment]
Closing this in favor of #26 which has more discussion and to reduce duplicated issues. :)
