### ISSUE TITLE
Allow users to change the color of the whitespace

### ISSUE THREAD

**Issue by ShimShamSam** [DennisKehrig/brackets-show-whitespace#26]
With themes becoming standard in 0.42, the color of the whitespace should not be hard coded. The whitespace is too bright on the newly added default dark theme, for instance. Would it be possible to add a setting to configure the color ourselves to best match the theme we are using?

**Comment by dimtref** [comment]
Hey guys, you can do it yourself. Go to the file 'main.less' and inside him fix background-color property from '#ccc' to '#686963' as shown in the picture:
![fix high bright whitespaces](https://cloud.githubusercontent.com/assets/9086217/5592499/a8b24d74-91e3-11e4-86ce-78b143f7db09.jpg)
After that click 'Save' and go to Debug->Reload With Extensions.

**Comment by le717** [comment]
I've submitted a PR (#30) that adds this. I'd love it if you guys would try it out for me. :)

**Comment by MiguelCastillo** [comment]
@le717 yes sir, I will be happy to.

**Comment by le717** [comment]
@MiguelCastillo :smile:

**Comment by MiguelCastillo** [comment]
@le717 I don't know what you had in mind, but you can hook into the theme selection events to get the theme...  You could then use something like this https://github.com/MiguelCastillo/Brackets-Themes/blob/master/ColorProcessor.js to automatically choose some colors :)

**Comment by le717** [comment]
@MiguelCastillo Are you referring to the default color options? I was not thinking anything. The light values are already used by the extension, and I just copied the hex value from https://github.com/DennisKehrig/brackets-show-whitespace/issues/26#issuecomment-68489114 for dark theme testing and kept red for trailing. Someone who is more color-inclined can define the default dark colors. My goal was to make them configurable. :)

**Comment by MiguelCastillo** [comment]
Yeah I was thinking of getting fancy for little reward...  I was thinking of automating the process of picking colors for the dots to best back the color background.  Making them configurable is great. Pardon my barging in here :)

**Comment by le717** [comment]
Ah, I see now. :) Np. I think that feature, although cool, is a bit out of scope of this issue and the PR, but it could always be added in a fork (seeing as @DennisKehrig has not been online since May 2014, an updated fork may be in order).

**Comment by DennisKehrig** [comment]
Hey guys! I know I've neglected this extension badly. That's unlikely to change much soon, veeery busy times right now. Would it help if I make somebody a contributor, so you can manage this repo? Might be easier than introducing an extension based on a fork. Who would want to do this?

**Comment by DennisKehrig** [comment]
On this particular issue, I was hoping that themes would just pick up the class names that my extension produces, and add styles for those as well. Did anyone try that? It's possible that my extension overwrites these, depending on the order, but technically there's always the [`!important`](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity#The_!important_exception) suffix for that. I think only the theme itself knows what the best whitespace color would be, so these seems to be a useful place to define it.

Any thoughts on this?

**Comment by DennisKehrig** [comment]
Looks like @sevenfoxes tried this (see #22)

**Comment by le717** [comment]
> Hey guys! I know I've neglected this extension badly. That's unlikely to change much soon, veeery busy times right now. Would it help if I make somebody a contributor, so you can manage this repo? Might be easier than introducing an extension based on a fork. Who would want to do this?

I wold not mind part-time managing this. There is not too much action related to this extension. I think I could handle it.

> On this particular issue, I was hoping that themes would just pick up the class names that my extension produces, and add styles for those as well. Did anyone try that? It's possible that my extension overwrites these, depending on the order, but technically there's always the !important suffix for that. I think only the theme itself knows what the best whitespace color would be, so this seems to be a useful place to define it.

I think a few themes over at https://github.com/Brackets-Themes define their own whitespace colors, but I don't recall it really catching on. I am not sure if #30 overwrites it or not, TBH. I'd have to check.

**Comment by MiguelCastillo** [comment]
@le717 @DennisKehrig I had included in [themes](https://github.com/MiguelCastillo/Brackets-Themes) some work for styling the white spaces but people always had some tweaks to the colors to make, so I took it out.

I could add theming related stuff in my themes extension again now that I have color detection...  I will do a lil work on this in the next couple of days. @le717 I will pull you in when I get this going.

**Comment by le717** [comment]
@MiguelCastillo Sounds good, but know ahead of time that I am horrible at color schemes (although I am trying to improve that). :P Also, classes start Wednesday, so free time will drop dramatically, but I should still be able to look at it. :+1:

@DennisKehrig While I like @MiguelCastillo's idea of auto-selecting colors, I still think we need the colors to be configurable from within the extension and have a nice color set to match Bracket's built-in light and dark themes (and for those who don't have the theme's extension installed). I am actually going to be helping my advisor install Brackets on the computers in his labs soon + a curated selection of extensions, including this one. I'd love to at least have the color configuration code in `master` so I can use it in setup so other students can benefit.

**Comment by DennisKehrig** [comment]
Hey @le717, I'm happy to hear it! I added you as a contributor. I won't have any time to work on this for the upcoming weeks (moving halfway across the globe), so for the time being, you are in complete control. :)

**Comment by le717** [comment]
> so for the time being, you are in complete control.

Don't worry, absolute power is not going to go to my head. ;)

I just remembered that the extension registry does not support multiple people uploading releases, so when you get back I should have a version ready and waiting for you to release. :)

Good luck with the move! I'm sure you'll have a ["fun"](https://twitter.com/_le717/status/522575070309650432) time!

**Comment by sevenfoxes** [comment]
Sorry I don't do brackets anymore haha

**Comment by le717** [comment]
This has been implemented by #31 and will be in the next extension release. In the mean time, you can always download the newest version from `master`. :smile: 

Closing.
