### ISSUE TITLE
Performance Issues Release 0.44 OSX

### ISSUE THREAD

**Issue by whaaaley** [DennisKehrig/brackets-show-whitespace#27]
I updated Brackets today and noticed a huge amount of lag. It took about 1-3 seconds for Brackets figure out I was trying to do anything and I noticed my CPU temp spiked from 60c to 85-90c with only Chrome and Brackets running.

I started removing all of of my plugins one by one. I only use a few. After I removed Show Whitespace everything was back to normal, mostly. Brackets still runs kind of slow, but it could be because of the whole split view things being new.

I have a newer MBP. There's no hardware reason for Brackets to be lagging.

I hope somehow you could get this fixed. This is one of my favorite plugins! I feel like my code is naked without it.

**Comment by le717** [comment]
@dustindowell22 @spidarmen CodeMirror overlays (how whitespace is visualized) always slows the editor down on any platform, but that does not mean the situation cannot be improved. Is the slowdown still as bad for you using the newest version of the extension and Brackets?

**Comment by dustindowell22** [comment]
@le717 I just re-installed. It seems to be less of a problem when using it alone, but still a tad slow when scrolling but it's tolerable. Typing is no longer causing as much lag, which is the main reason I had to disable it. But still, if I look carefully, I can still see some lag. Does the whole document get updated on keypress or just the current line? Also, I use 2 spaces for indents and I'd assume that would cause twice as many `spans` as tabs would, right? If so, maybe two spaces could combine into a single span with two dot characters when the indents are set to spaces.
