### ISSUE TITLE
Want add a new style like sublime2 

### ISSUE THREAD

**Issue by Sean-Wang** [DennisKehrig/brackets-show-whitespace#33]
![snip20150123_1](https://cloud.githubusercontent.com/assets/1193073/5870311/92bd132c-a305-11e4-9dd8-db7863e18419.png)

**Comment by le717** [comment]
I have never used Sublime 2, can you clarify a bit on your request and what is highlighted in your image?

**Comment by le717** [comment]
Looking at your image more carefully,  I can tell you are looking for the [Indent Guides](https://github.com/lkcampbell/brackets-indent-guides) extension, which does just as you want. :) Closing.
