### ISSUE TITLE
Lodash 3.x support

### ISSUE THREAD

**Issue by le717** [DennisKehrig/brackets-show-whitespace#34]
As part of #31, I've introduced a dependency on Lodash, which is available in Brackets core. There are plans of updating Brackets to use the new version, and in doing so, the new usage of `._template` might break. Track progress of the upgrade and update this extension accordingly.

#### References ####
* adobe/brackets#10550
* https://github.com/lodash/lodash/wiki/Changelog

**Comment by MarcelGerber** [comment]
I think the way you you call `_.template` is still supported, isn't it?

**Comment by le717** [comment]
Double checking, it looks like it may be, yes. Once a patch for Brackets to update Lodash is available, I'll pull it, test the extension against it, and update this issue.

**Comment by MarcelGerber** [comment]
You can use my branch https://github.com/MarcelGerber/brackets/tree/lodash-3

**Comment by le717** [comment]
Good, then I'll test with that.

**Comment by le717** [comment]
Just tested this with the latest Brackets `master` and you were correct Marcel, the way I am calling `_.template` is still supported. Closing.
