### ISSUE TITLE
Opacity

### ISSUE THREAD

**Issue by BrianDGLS** [DennisKehrig/brackets-show-whitespace#40]
Hi,

The current opacity can be quite intrusive.

Can I suggest an addition to lines 44 and 53 of main.less.

Adding in the following:

opacity: 0.2;

A really useful plugin.

Thanks,

Brian

**Comment by le717** [comment]
Hmmm... I've never thought about that. I would actually not hardcode the opacity value (Brackets not too recently did that with split view and made a lot of people upset) but rather make it a preference, but I think it's something we could do.

**Comment by BrianDGLS** [comment]
Cool. Here is a before and after just to show what I mean.

Before:
![screen shot 2015-03-27 at 20 16 19](https://cloud.githubusercontent.com/assets/7824734/6876347/6c0f45ac-d4be-11e4-836b-72f1a9e73ac7.png)

After:
![screen shot 2015-03-27 at 20 17 27](https://cloud.githubusercontent.com/assets/7824734/6876350/75bb355c-d4be-11e4-81bb-cf2c6b806685.png)

**Comment by le717** [comment]
I do see what you mean! I'll toy around with the exact opacity value, as `0.2` may not be the best general value. :wink:

**Comment by le717** [comment]
BTW, just an off-topic note here, you might try normalizing your input in your Python scripts. I've a tutorial on that concept [here](https://triangle717.wordpress.com/tutorials/python/normalize-user-input/). :smiley:

**Comment by le717** [comment]
I should have asked this already, but you download the latest code from the `master` branch and tell me if you still think the opacity is still needed? I just remembered that I've added dark theme complementing colors, and those should be checked with and without the opacity added as well.

**Comment by lkcampbell** [comment]
What would be even better is to make the color of the white space indicators a User Preference since you don't know ahead of time which color will look correct on a given background color.

**Comment by le717** [comment]
@lkcampbell I did that in #31. Once @DennisKehrig gets back and makes a release, it will finally be available to all. :)

**Comment by lkcampbell** [comment]
Oh oops, should have read the entire thread first :). Good job!

**Comment by le717** [comment]
Thanks. I'm wondering now if an opacity setting is really required, as I momentarily forgot about the preferences when I said I could add this.

**Comment by le717** [comment]
@BrianDGLS Thanks for the feature idea, but I am going to decide against this as the latest code now has proper dark theme support. If you will, please download the latest code from the `master` branch and see if that works for you. Afterward, if you think opacity is still needed, reopen this along with your reasoning for the addition. :)
