### ISSUE TITLE
Is there a way to turn off viewing of tab symbols in the document

### ISSUE THREAD

**Issue by wyattbiker** [DennisKehrig/brackets-show-whitespace#41]
I posted this to the brackets forum. Screen shot at bottom. Thanks!

https://groups.google.com/forum/#!searchin/brackets-dev/wyattbiker/brackets-dev/wdNtb7UDs7Q/NaQ_0I6B4qoJ

**Comment by le717** [comment]
Can you repost the picture here? I cannot seem to load it in the forum.

**Comment by le717** [comment]
Closing as this does not pertain to this extension.
