### ISSUE TITLE
Option to show the "space marks" following the indentation settings

### ISSUE THREAD

**Issue by rogeriotaques** [DennisKehrig/brackets-show-whitespace#45]
The brackets-show-whitespace is doing a great work at all. Thanks. Anyway, I'd like to suggest an enhancement that may improve the user experience.

In the current version, we get something like:

```
<!DOCTYPE html>
<html lang="en">
..<head>
....<meta charset="utf-8">
..</head>
..<body>
....<p>...</p>
....<div>
......<div>
........<p>...</p>
........<p>...</p>
........<p>...</p>
......</div>
....</div>
..</body>
</html>
```

In order to make the code view cleaner, it could be nice if there is an option to only show the "space mark" on indentation points, e.g: same as Sublime Text does. So, we would get something like:

```
<!DOCTYPE html>
<html lang="en">
  <head>
  . <meta charset="utf-8">
  .  </head>
  .  <body>
  .  .  <p>...</p>
  .  .  <div>
  .  .  .  <div>
  .  .  .  .  <p>...</p>
  .  .  .  .  <p>...</p>
  .  .  .  .  <p>...</p>
  .  .  .  </div>
  .  .  </div>
  .  </body>
</html>
```

**Comment by le717** [comment]
This sounds like an interesting idea! Can you snap a picture of this in Sublime (using the example code given) so I can get a better idea of what it needs to go on?

In the mean time, you might want to give the [Indent Guides](https://github.com/lkcampbell/brackets-indent-guides) extension a try.

**Comment by rogeriotaques** [comment]
Hey Dennis.

Thanks for your reply.

I haven't any snapshot now, sorry. I tried the indent guide and it's
exactly what I did mean.

If your extension could have a close feature, should be perfect. Even more
perfect if this feature could be "customized" in a property panel, where
you can change colors or styles (dots, strokes, etc).

Roger.

Em terça-feira, 23 de junho de 2015, Triangle717 <notifications@github.com>
escreveu:

**Comment by le717** [comment]
Actually, I'm not Dennis. He's away right now and I'm in charge. :)

> I tried the indent guide and it's exactly what I did mean.

That's great to hear!

> If your extension could have a close feature, should be perfect. 

Close as in turn off? Go to View > Show Whitespace.

> Even more perfect if this feature could be "customized" in a property panel, where you can change colors or styles (dots, strokes, etc).

If you nab the latest code from the `master` branch (see installation method 2 in the README), you can customize the colors via the Brackets' preferences file. :)

**Comment by rogeriotaques** [comment]
Wow! I'm sorry Caleb!
I didn't know that.

Actually, I tried to say "similar" when said "close". I meant, if the
brackets-show-whitespaces can have a feature more like the "Indent Guide"
will be perfect.

Anyway, thank you very much for your attention and time. :)

Roger.

Em quarta-feira, 24 de junho de 2015, Caleb Ely <notifications@github.com>
escreveu:

**Comment by rogeriotaques** [comment]
After 5 years pending, it doesn't seem we'll see this again. Closing.
